# Generated by Django 5.0.1 on 2024-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_code', models.CharField(max_length=200)),
                ('organisation_description', models.TextField()),
                ('organisation_website', models.CharField(max_length=200)),
                ('organisation_logo', models.ImageField(default='default_logo.png', upload_to='media/logos')),
            ],
        ),
    ]
