# Generated by Django 5.0.1 on 2024-01-17 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_id', models.UUIDField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('venue_name', models.CharField(default='venue', max_length=200)),
                ('venue_postcode', models.CharField(default='None', max_length=200)),
                ('venue_country', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('ZOOM', 'Zoom'), ('GOOGLE MEET', 'Google meet'), ('YOUTUBE', 'YouTube'), ('SKYPE', 'Skype'), ('VIMEO', 'Vimeo'), ('FACEBOOK', 'Facebook'), ('OTHER', 'Other')], default='ZOOM', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tickets_available', models.IntegerField()),
                ('tickets_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(default='admin', max_length=200)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_code', models.CharField(max_length=200)),
                ('job_link', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_code', models.CharField(max_length=200)),
                ('organisation_description', models.TextField()),
                ('organisation_website', models.CharField(max_length=200)),
                ('organisation_logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
