# Generated by Django 5.0.1 on 2024-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(default='default_logo.png', upload_to='media/logos'),
        ),
    ]
