# Generated by Django 4.2.6 on 2023-10-11 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Approved'), (False, 'Pending')], default=False)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERSHIP', 'Internship')], default='FT', max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('url', models.URLField(default='www.tumpetech.com')),
                ('email', models.EmailField(default='info@tumpetech.com', max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
                ('district', models.CharField(choices=[('CHADIZA', 'Chadiza'), ('CHAMA', 'Chama'), ('CHANDESI', 'Chandesi'), ('CHAVUMA', 'Chavuma'), ('CHEMBE', 'Chembe'), ('CHIBOMBO', 'Chibombo'), ('CHIENGI', 'Chiengi'), ('CHILANGA', 'Chilanga'), ('CHILUBI', 'Chilubi'), ('CHILILABOMBWE', 'Chililabombwe'), ('CHINGOLA', 'Chingola'), ('CHIPATA', 'Chipata'), ('CHINSALI', 'Chinsali'), ('CHINYINGI', 'Chinyingi'), ('CHIRUNDU', 'Chirundu'), ('CHISAMBA', 'Chisamba'), ('CHOMA', 'Choma'), ('CHONGWE', 'Chongwe'), ('GWEMBE', 'Gwembe'), ('IKELENGE', 'Ikelenge'), ('ISOKA', 'Isoka'), ('ITEZHI', 'Itezhi Tezhi'), ('KABOMPO', 'Kabompo'), ('KABWE', 'Kabwe'), ('KAFUE', 'Kafue'), ('KAFULWE', 'Kafulwe'), ('KALABO', 'Kalabo'), ('KALOMO', 'Kalomo'), ('KALULUSHI', 'Kalulushi'), ('KANYEMBO', 'Kanyembo'), ('KAOMA', 'Kaoma'), ('KAPIRI', 'Kapiri Mposhi'), ('KAPUTA', 'Kaputa'), ('KASAMA', 'Kasama'), ('KASEMPA', 'Kasempa'), ('KASHIKISHI', 'Kashikishi'), ('KATABA', 'Kataba'), ('KATETE', 'Katete'), ('KAWAMBWA', 'Kawambwa'), ('KAZEMBE', 'Kazembe'), ('KAZUNGULA', 'Kazungula'), ('KIBOMBOBENE', 'Kibombomene'), ('KITWE', 'Kitwe'), ('LIVINGSTONE', 'Livingstone'), ('LUANSHYA', 'Luanshya'), ('LUANGWA', 'Luangwa'), ('LUFWANYAMA', 'Lufwanyama'), ('LUKULU', 'Lukulu'), ('LUNDAZI', 'Lundazi'), ('LUSAKA', 'Lusaka'), ('LUWINGU', 'Luwingu'), ('MACHA', 'Macha'), ('MAFINGA', 'Mafinga'), ('MAKENI', 'Makeni'), ('MAMBWE', 'Mambwe'), ('MANSA', 'Mansa'), ('MASAITI', 'Masaiti'), ('MAZABUKA', 'Mazabuka'), ('MBALA', 'Mbala'), ('MBERESHI', 'Mbereshi'), ('MFUWE', 'Mfuwe'), ('MILENGE', 'Milenge'), ('MISISI', 'Misisi'), ('MKUSHI', 'Mkushi'), ('MONGU', 'Mongu'), ('MONZE', 'Monze'), ('MPIKA', 'Mpika'), ('MPONGWE', 'Mpongwe'), ('MPOROKOSO', 'Mporokoso'), ('MPULUNGU', 'Mpulungu'), ('MUFULIRA', 'Mufulira'), ('MUFUMBWE', 'Mufumbwe'), ('MUMBWA', 'Mumbwa'), ('MUNGWI', 'Mungwi'), ('MWENSE', 'Mwense'), ('MUYOMBE', 'Muyombe'), ('MWINILUNGA', 'Mwinilunga'), ('NAKONDE', 'Nakonde'), ('NAMWALA', 'Namwala'), ('NCHELENGE', 'Nchelenge'), ('NDOLA', 'Ndola'), ('NGOMA', 'Ngoma'), ('NKANA', 'Nkana'), ('NSELUKA', 'Nseluka'), ('NYIMBA', 'Nyimba'), ('PEMBA', 'Pemba'), ('PETAUKE', 'Petauke'), ('RUFUNSA', 'Rufunsa'), ('SAMFYA', 'Samfya'), ('SENANGA', 'Senanga'), ('SERENJE', 'Serenje'), ('SESHEKE', 'Sesheke'), ('SHANGONMBO', 'Shangombo'), ('SHIWANG_ANGU', "Shiwang'andu"), ('SIAVONGA', 'Siavonga'), ('SIKALONGO', 'Sikalongo'), ('SINAZONGWE', 'Sinazongwe'), ('SOLWEZI', 'Solwezi'), ('ZAMBEZI', 'Zambezi'), ('ZIMBA', 'Zimba')], default='LSK', max_length=30)),
                ('province', models.CharField(choices=[('CENTRAL', 'Central'), ('COPPERBELT', 'Copperbelt'), ('EASTERN', 'Eastern'), ('LUAPULA', 'Luapula'), ('LUSAKA_P', 'Lusaka'), ('NORTHERN', 'Northern'), ('NORTH_WESTERN', 'North Western'), ('MUCHINGA', 'Muchinga'), ('WESTERN', 'Western'), ('SOUTHERN', 'Southern')], default='LSKP', max_length=30)),
                ('industry', models.CharField(choices=[('ACADEMIA', 'Academia'), ('ACCOUNTANCY', 'Accountancy'), ('ADMINISTRATION', 'Administration'), ('AGRICULTURE', 'Agriculture'), ('BANKING_AND_FINANCE', 'Banking and Finance'), ('DEVELOPMENT', 'Development'), ('ENGINEERING_AND_CONSTRUCTION', 'Engineering and Construction'), ('HEALTH', 'Health'), ('HUMAN_RESOURCE', 'Human Resource'), ('ICT_AND_TELCO', 'ICT and Telco'), ('LAW', 'Law'), ('MANUFACTURING_FMCG', 'Manufacturing/FMCG'), ('OTHER', 'Other'), ('PUBLIC_SECTOR', 'Public Sector'), ('RETAIL_AND_SALES', 'Retail and Sales'), ('TRANSPORT_AND_LOGISTICS', 'Transport and Logistics')], default='EDU', max_length=30)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
