# Generated by Django 4.1.5 on 2023-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(
                        default="", max_length=250, unique_for_date="post_date"
                    ),
                ),
                ("post_date", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField()),
                ("location", models.CharField(max_length=50)),
                ("details", models.TextField()),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("ACCOUNTACY", "Accountancy"),
                            ("ADMINISTARTION", "Administration"),
                            ("AGRICULTURE", "Agriculture"),
                            ("BANKING_AND_FINANCE", "Banking and Finance"),
                            ("DEVELOPMENT", "Development"),
                            ("EDUCATION", "Education"),
                            (
                                "ENGINEERING_AND_CONSTRUCTION",
                                "Engineering and Construction",
                            ),
                            ("HEALTH", "Health"),
                            ("HUMAN_RESOURCE", "Human Resource"),
                            ("ICT_AND_TELECO", "ICT and Telco"),
                            ("LEGAL", "Legal"),
                            ("MANUFACTURING_FMCG", "Manufacturing/FMCG"),
                            ("OTHER", "Other"),
                            ("PUBLIC_SECTOR", "Public Sector"),
                            ("RETAIL_AND_SALES", "Retail and Sales"),
                            ("TRANSPORT_AND_LOGISTICS", "Transport and Logistics"),
                        ],
                        default="ACC",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
