# Generated by Django 5.0.1 on 2024-01-29 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='job_like', to=settings.AUTH_USER_MODEL),
        ),
    ]

