# Generated by Django 4.1.4 on 2023-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="url",
            field=models.URLField(default=None),
        ),
    ]
