# Generated by Django 5.0.1 on 2024-01-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='organisation',
        ),
    ]
