# Generated by Django 4.1.4 on 2023-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0002_job_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="email",
            field=models.EmailField(
                default="chepplethwaite@tumpetech.com", max_length=254
            ),
        ),
    ]
