# Generated by Django 4.2.11 on 2024-03-21 00:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_job_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
