# Generated by Django 5.0.1 on 2024-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_rename_company_job_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='logos_default.jpg', upload_to='media/logos'),
        ),
    ]
