# Generated by Django 4.1.5 on 2023-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0002_job_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ACCOUNTACY", "Accountancy"),
                    ("ADMINISTARTION", "Administration"),
                    ("AGRICULTURE", "Agriculture"),
                    ("BANKING_AND_FINANCE", "Banking and Finance"),
                    ("DEVELOPMENT", "Development"),
                    ("EDUCATION", "Education"),
                    ("ENGINEERING_AND_CONSTRUCTION", "Engineering and Construction"),
                    ("HEALTH", "Health"),
                    ("HUMAN_RESOURCE", "Human Resource"),
                    ("ICT_AND_TELECO", "ICT and Telco"),
                    ("LEGAL", "Legal"),
                    ("MANUFACTURING_FMCG", "Manufacturing/FMCG"),
                    ("OTHER", "Other"),
                    ("PUBLIC_SECTOR", "Public Sector"),
                    ("RETAIL_AND_SALES", "Retail and Sales"),
                    ("TRANSPORT_AND_LOGISTICS", "Transport and Logistics"),
                ],
                default="ACC",
                max_length=255,
            ),
        ),
    ]
