# Generated by Django 4.1.4 on 2023-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0003_job_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="email",
            field=models.EmailField(default="info@tumpetech.com", max_length=254),
        ),
    ]
