# Generated by Django 4.1.5 on 2023-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0004_alter_job_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="approval_status",
            field=models.BooleanField(
                choices=[("True", "Approved"), ("False", "Pending")], default=False
            ),
        ),
    ]
