# Generated by Django 4.1.5 on 2023-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0005_job_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="approval_status",
            field=models.BooleanField(
                choices=[(True, "Approved"), (False, "Pending")], default=False
            ),
        ),
    ]
