# Generated by Django 5.0.1 on 2024-01-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_alter_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(default='https://www.example.com/link-to-job/'),
        ),
    ]
