# Generated by Django 4.1.5 on 2023-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0006_alter_job_approval_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="approval_status",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="job",
            name="url",
            field=models.URLField(default="www.tumpetech.com"),
        ),
    ]
