# Generated by Django 5.0.1 on 2024-01-18 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_alter_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='Lusaka', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='Zambia', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
