# Generated by Django 5.0.1 on 2024-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_job_city_job_country_alter_job_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='district',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='province',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('N/A', 'n/a'), ('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERSHIP', 'Internship')], default='FT', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('OTHER', 'Other'), ('ACADEMIA', 'Academia'), ('ACCOUNTANCY', 'Accountancy'), ('ADMINISTRATION', 'Administration'), ('AGRICULTURE', 'Agriculture'), ('BANKING_AND_FINANCE', 'Banking and Finance'), ('DEVELOPMENT', 'Development'), ('ENGINEERING_AND_CONSTRUCTION', 'Engineering and Construction'), ('HEALTH', 'Health'), ('HUMAN_RESOURCE', 'Human Resource'), ('ICT_AND_TELCO', 'ICT and Telco'), ('LAW', 'Law'), ('MANUFACTURING_FMCG', 'Manufacturing/FMCG'), ('PUBLIC_SECTOR', 'Public Sector'), ('RETAIL_AND_SALES', 'Retail and Sales'), ('TRANSPORT_AND_LOGISTICS', 'Transport and Logistics')], default='EDU', max_length=30),
        ),
    ]
