# Generated by Django 5.0.1 on 2024-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_remove_job_city_remove_job_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='media/logos'),
        ),
    ]
