# Generated by Django 5.0.1 on 2024-01-18 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_alter_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
