# Generated by Django 5.0.1 on 2024-01-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_job_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='uuid',
        ),
    ]
