# Generated by Django 5.0.1 on 2024-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0011_remove_job_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(choices=[('N/A', 'n/a'), ('CHADIZA', 'Chadiza'), ('CHAMA', 'Chama'), ('CHANDESI', 'Chandesi'), ('CHAVUMA', 'Chavuma'), ('CHEMBE', 'Chembe'), ('CHIBOMBO', 'Chibombo'), ('CHIENGI', 'Chiengi'), ('CHILANGA', 'Chilanga'), ('CHILUBI', 'Chilubi'), ('CHILILABOMBWE', 'Chililabombwe'), ('CHINGOLA', 'Chingola'), ('CHIPATA', 'Chipata'), ('CHINSALI', 'Chinsali'), ('CHINYINGI', 'Chinyingi'), ('CHIRUNDU', 'Chirundu'), ('CHISAMBA', 'Chisamba'), ('CHOMA', 'Choma'), ('CHONGWE', 'Chongwe'), ('GWEMBE', 'Gwembe'), ('IKELENGE', 'Ikelenge'), ('ISOKA', 'Isoka'), ('ITEZHI', 'Itezhi Tezhi'), ('KABOMPO', 'Kabompo'), ('KABWE', 'Kabwe'), ('KAFUE', 'Kafue'), ('KAFULWE', 'Kafulwe'), ('KALABO', 'Kalabo'), ('KALOMO', 'Kalomo'), ('KALULUSHI', 'Kalulushi'), ('KANYEMBO', 'Kanyembo'), ('KAOMA', 'Kaoma'), ('KAPIRI', 'Kapiri Mposhi'), ('KAPUTA', 'Kaputa'), ('KASAMA', 'Kasama'), ('KASEMPA', 'Kasempa'), ('KASHIKISHI', 'Kashikishi'), ('KATABA', 'Kataba'), ('KATETE', 'Katete'), ('KAWAMBWA', 'Kawambwa'), ('KAZEMBE', 'Kazembe'), ('KAZUNGULA', 'Kazungula'), ('KIBOMBOBENE', 'Kibombomene'), ('KITWE', 'Kitwe'), ('LIVINGSTONE', 'Livingstone'), ('LUANSHYA', 'Luanshya'), ('LUANGWA', 'Luangwa'), ('LUFWANYAMA', 'Lufwanyama'), ('LUKULU', 'Lukulu'), ('LUNDAZI', 'Lundazi'), ('LUSAKA', 'Lusaka'), ('LUWINGU', 'Luwingu'), ('MACHA', 'Macha'), ('MAFINGA', 'Mafinga'), ('MAKENI', 'Makeni'), ('MAMBWE', 'Mambwe'), ('MANSA', 'Mansa'), ('MASAITI', 'Masaiti'), ('MAZABUKA', 'Mazabuka'), ('MBALA', 'Mbala'), ('MBERESHI', 'Mbereshi'), ('MFUWE', 'Mfuwe'), ('MILENGE', 'Milenge'), ('MISISI', 'Misisi'), ('MKUSHI', 'Mkushi'), ('MONGU', 'Mongu'), ('MONZE', 'Monze'), ('MPIKA', 'Mpika'), ('MPONGWE', 'Mpongwe'), ('MPOROKOSO', 'Mporokoso'), ('MPULUNGU', 'Mpulungu'), ('MUFULIRA', 'Mufulira'), ('MUFUMBWE', 'Mufumbwe'), ('MUMBWA', 'Mumbwa'), ('MUNGWI', 'Mungwi'), ('MWENSE', 'Mwense'), ('MUYOMBE', 'Muyombe'), ('MWINILUNGA', 'Mwinilunga'), ('NAKONDE', 'Nakonde'), ('NAMWALA', 'Namwala'), ('NCHELENGE', 'Nchelenge'), ('NDOLA', 'Ndola'), ('NGOMA', 'Ngoma'), ('NKANA', 'Nkana'), ('NSELUKA', 'Nseluka'), ('NYIMBA', 'Nyimba'), ('PEMBA', 'Pemba'), ('PETAUKE', 'Petauke'), ('RUFUNSA', 'Rufunsa'), ('SAMFYA', 'Samfya'), ('SENANGA', 'Senanga'), ('SERENJE', 'Serenje'), ('SESHEKE', 'Sesheke'), ('SHANGONMBO', 'Shangombo'), ('SHIWANG_ANGU', "Shiwang'andu"), ('SIAVONGA', 'Siavonga'), ('SIKALONGO', 'Sikalongo'), ('SINAZONGWE', 'Sinazongwe'), ('SOLWEZI', 'Solwezi'), ('ZAMBEZI', 'Zambezi'), ('ZIMBA', 'Zimba')], default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='province',
            field=models.CharField(choices=[('N/A', 'n/a'), ('CENTRAL', 'Central'), ('COPPERBELT', 'Copperbelt'), ('EASTERN', 'Eastern'), ('LUAPULA', 'Luapula'), ('LUSAKA_P', 'Lusaka'), ('NORTHERN', 'Northern'), ('NORTH_WESTERN', 'North Western'), ('MUCHINGA', 'Muchinga'), ('WESTERN', 'Western'), ('SOUTHERN', 'Southern')], default='N/A', max_length=30),
        ),
    ]
