# Generated by Django 5.0.1 on 2024-01-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_job_district_job_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='district',
            new_name='location',
        ),
    ]
