# Generated by Django 5.0.1 on 2024-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0013_rename_district_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
