# Generated by Django 4.1.5 on 2023-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0014_alter_job_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ACADEMIA", "Academia"),
                    ("ACCOUNTANCY", "Accountancy"),
                    ("ADMINISTRATION", "Administration"),
                    ("AGRICULTURE", "Agriculture"),
                    ("BANKING_AND_FINANCE", "Banking and Finance"),
                    ("DEVELOPMENT", "Development"),
                    ("ENGINEERING_AND_CONSTRUCTION", "Engineering and Construction"),
                    ("HEALTH", "Health"),
                    ("HUMAN_RESOURCE", "Human Resource"),
                    ("ICT_AND_TELCO", "ICT and Telco"),
                    ("LAW", "Law"),
                    ("MANUFACTURING_FMCG", "Manufacturing/FMCG"),
                    ("OTHER", "Other"),
                    ("PUBLIC_SECTOR", "Public Sector"),
                    ("RETAIL_AND_SALES", "Retail and Sales"),
                    ("TRANSPORT_AND_LOGISTICS", "Transport and Logistics"),
                ],
                default="EDU",
                max_length=255,
            ),
        ),
    ]
