# Generated by Django 5.0.1 on 2024-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0014_alter_job_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='job', max_length=250),
        ),
    ]
