# Generated by Django 4.1.4 on 2023-05-02 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0015_alter_job_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
