# Generated by Django 5.0.1 on 2024-01-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0016_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Pending')], default=True),
        ),
    ]
