# Generated by Django 4.1.4 on 2023-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0016_alter_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("TEMPORARY", "Temporary"),
                    ("INTERSHIP", "Internship"),
                ],
                default="FT",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ACADEMIA", "Academia"),
                    ("ACCOUNTANCY", "Accountancy"),
                    ("ADMINISTRATION", "Administration"),
                    ("AGRICULTURE", "Agriculture"),
                    ("BANKING_AND_FINANCE", "Banking and Finance"),
                    ("DEVELOPMENT", "Development"),
                    ("ENGINEERING_AND_CONSTRUCTION", "Engineering and Construction"),
                    ("HEALTH", "Health"),
                    ("HUMAN_RESOURCE", "Human Resource"),
                    ("ICT_AND_TELCO", "ICT and Telco"),
                    ("LAW", "Law"),
                    ("MANUFACTURING_FMCG", "Manufacturing/FMCG"),
                    ("OTHER", "Other"),
                    ("PUBLIC_SECTOR", "Public Sector"),
                    ("RETAIL_AND_SALES", "Retail and Sales"),
                    ("TRANSPORT_AND_LOGISTICS", "Transport and Logistics"),
                ],
                default="EDU",
                max_length=30,
            ),
        ),
    ]
