# Generated by Django 4.1.4 on 2023-05-10 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0017_job_employment_type_alter_job_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="post_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
