# Generated by Django 5.0.1 on 2024-01-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0018_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
