# Generated by Django 4.1.4 on 2023-05-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0018_job_post_id_alter_job_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="post_id",
        ),
    ]
