# Generated by Django 5.0.1 on 2024-01-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0019_remove_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='organisation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
