# Generated by Django 5.0.1 on 2024-01-26 01:09

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0021_remove_job_province_job_country_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
