# Generated by Django 5.0.1 on 2024-01-26 01:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0022_alter_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(default='select country', max_length=2),
        ),
    ]
