# Generated by Django 4.1.4 on 2023-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_app", "0022_alter_job_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(default="", max_length=250),
        ),
    ]
